---
title: "README.md"
author: "Justin Peabody"
date: "2026-10-06"
output: html_document
---

Welcome to the repository housing my Predictive Analytics semester project! This project utilizes historical data from the PurpleAir sensor network, which I already have access to as the Database Manager for Loyola University's Community Engaged Local Air Research (CLEAR) lab (see the repositories Summer_2026_Air_Quality_Research and CLEAR_lab_database_management_2026_2027 for details). 

## Contents of this repository:

#### This README file


#### STAT_338_Project_Codes.md: 

a Markdown file containing all the R code used to build predictive models of changes in air pollution concentrations, using changes in humidity, temperature, and pressure, in addition to the distances between each sensor and the three nearest known pollution sources and the amount of PM2.5 emitted by those sources in 2025.

#### STAT_338_Project_Paper.md: 

The final deliverable of the project. A html file containing a formal, highly detailed academic write up of my project process, including data sources, acquisition, and preprocessing steps, the models used for prediction and inference purposes, the methodology of customizing feature selection and cross validation workflows, the selection of two final models (one for inference, and one for prediction), a consideration of each model's strengths and limitations, and an Appendix containing the code in STAT_338_Project_Codes.md to ensure reproducibility of my work. The repository STAT_308_Final_Project does not contain such a write up because it was composed as a Google Doc.






